baseURL: https://Cuudemi.github.io./cuudemi_pictures # todo: change site url.
publishDir: "docs"


title: Cuudemi's Pictures
defaultContentLanguage: 'en'
theme: eternity

params:
  image: /images/banner.png
  logo: logo.png
  subtitle: Здесь хранятся мои фото дял души :)
  copyright: All rights reserved
  author: Shcheglova Anastasia Andreevna
  dontShowSource: false
  portfolio:
    columns:
      desktop:
        nature: 4
        archive: 6
        kittens: 4
        default: 3
      mobile:
        default: 2
        archive: 3
  socials:
    # todo: change these links.
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:anaastasia912@gmail.com'
      landing: true
    - icon: 'fab fa-github fa-lg'
      url: 'https://github.com/Cuudemi/cuudemi_pictures'
      landing: true
  homepage: "/nature"
  specialPages:
    - nature
    - archive
  bypassWelcomePage: false
  disableWelcomePageBackground: false
  disableRadius: false
  moveIt: false
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  nature: ":filename/"

menu:
  main:
    - name: природа 
      url: /nature/
      weight: 1
    - name: котята (не мои)
      url: /tags/kittens/
      weight: 2
    - name: все фото вместе
      url: /tags/archive/
      weight: 4
    - name: обо мне
      url: /about/
      weight: 5
